### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by rottenwheel** [prodezzargenta/open-source-brands#1]
Algunas correcciones o sugerencias para el documento.

3.2
- Página 14. "Community Crowdfunded System" - [Community Crowdfunding System](https://ccs.getmonero.org/).
- Página 15. Incentivo económico. "...realizar buscar" - Podrías remover realizar; dos verbos consecutivos confunden al lector.

3.2.1
- Página 17. "¿Cómo el cliente podría asegurarse que el producto que desea comprar es auténtico y no una falsificación?" - [Queísmo](https://kitzalet.com/editorial-digital/queismo-y-dequeismo-cuando-usar-cada-uno/). De que sería lo apropiado en este caso. Consideraría cambiar "es" por sea, pero es algo más personal que pragmático.

**Comment by prodezzargenta** [comment]
Corregido
